# Generated by Django 4.1.3 on 2022-11-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_todotask_id_todotask_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
